// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ankngizkajsebhlllsrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFua25naXprYWpzZWJobGxsc3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTY5NDUsImV4cCI6MjA1ODczMjk0NX0.DU93wU7JW0XDm23E7syZfNDUPH2TykVVE9wBZliu7do";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);